version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/hinzu-rustc-driver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/adapters/typescript"
    schedule:
      interval: "weekly"
