//! Structural-signature extraction from monomorphized MIR — the resolved-type
//! Rust path behind `hinzu similar --rust-extractor stablemir`.
//!
//! Where `structural_rust.rs` (the CLI's `syn` extractor) reads types, calls, and
//! control flow *syntactically*, this reduces the SAME `StructuralSignature` shape
//! (identical JSON field names — see `hinzu_core::similarity`) from the compiler's
//! own MIR, AFTER type resolution and monomorphization. That buys three honest
//! wins the syn path cannot have:
//!
//!   * **Resolved types.** A signature's parameter/return types are the compiler's
//!     resolved types, so a type ALIAS (`type Bytes = Vec<u8>`) collapses to its
//!     underlying constructor (`Vec<_>`) instead of an opaque leaf, and a concrete
//!     function's slots are the real types — two differently-written-but-identical
//!     types match. Leaf/parameter identities are still erased to `_` (so
//!     `Vec<User>`/`Vec<Order>` both shape to `Vec<_>`) — the "same shape,
//!     different types" signal is intact and desired.
//!   * **Resolved call targets.** The call sequence is the MIR `Call`
//!     terminators' resolved callees (via the driver's `fndef_name`), not a
//!     name-matched guess.
//!   * **Macro-expanded bodies.** MIR is post-expansion, so logic generated by a
//!     macro is visible in the histogram / shingles / calls rather than opaque.
//!
//! The cost, stated where the profile records it (`profile.rs`): source-level
//! structured nesting is lowered away (so `max_nesting` is not faithfully
//! recoverable and reads 0), the CFG is flat basic blocks (branch vs match and
//! loops are read best-effort from `SwitchInt` fan-out and back-edges), and
//! indirect dispatch (fn-pointer / `dyn`) is still unresolved. A generic function
//! is signed from its polymorphic body, so its type *parameters* appear as `_`
//! (unresolved, like syn) — the resolution win lands on concrete functions and on
//! aliases in any signature.

use std::collections::BTreeMap;

use rustc_public::mir::{Body, StatementKind, SwitchTargets, TerminatorKind};
use rustc_public::ty::{GenericArgKind, RigidTy, Ty, TyKind};
use rustc_public::CrateDef;
use serde::Serialize;

use crate::{fndef_name, strip_generics};

/// The k in the k-gram shingles, fixed to match the engine and the other
/// extractors (`hinzu_core::similarity::SHINGLE_K`).
const SHINGLE_K: usize = 3;

/// The document one wrapped crate emits, in `hinzu_core::similarity::SignatureDoc`
/// shape: the CLI adapter reads each `sigs-<crate>-<pid>.json` and concatenates
/// the `signatures`.
#[derive(Serialize)]
pub struct SigDoc {
    pub language: String,
    pub extractor: String,
    pub signatures: Vec<Signature>,
}

/// One function/method's structural fingerprint, field-for-field the JSON shape of
/// `hinzu_core::similarity::StructuralSignature` (so it deserializes straight
/// through the engine).
#[derive(Serialize)]
pub struct Signature {
    pub symbol_id: String,
    pub display: String,
    pub language: String,
    pub kind: String,
    pub file: String,
    pub line_start: u32,
    pub line_end: u32,
    pub arity: Arity,
    pub cfg: Cfg,
    pub stmt_histogram: BTreeMap<String, u32>,
    pub call_sequence: Vec<String>,
    pub type_shape: TypeShape,
    pub shingles: Vec<u64>,
    pub token_len: u32,
    pub features: BTreeMap<String, String>,
}

#[derive(Serialize, Default)]
pub struct Arity {
    pub params: u32,
    pub results: u32,
    pub generics: u32,
}

#[derive(Serialize, Default)]
pub struct Cfg {
    pub branch_count: u32,
    pub match_arms: u32,
    pub loop_count: u32,
    pub try_count: u32,
    pub return_points: u32,
    pub max_nesting: u32,
}

#[derive(Serialize, Default)]
pub struct TypeShape {
    pub params: Vec<String>,
    pub result: String,
}

/// Build a structural signature for a fn-like item from its type + MIR body.
/// Returns `None` when `ty` is not a function type (a `static`/`const`/closure has
/// no fn signature to shape), so callers can pass any walked item unconditionally.
pub fn build_signature(
    symbol_id: String,
    ty: Ty,
    body: &Body,
    file: String,
    line_start: u32,
    line_end: u32,
    kind: &str,
) -> Option<Signature> {
    let sig = ty.kind().fn_sig()?;
    let sig = sig.skip_binder();
    // `inputs_and_output` is params… then the single return type.
    let (output, params) = sig.inputs_and_output.split_last()?;

    let arity = Arity {
        params: params.len() as u32,
        results: if is_unit(*output) { 0 } else { 1 },
        // Post-monomorphization there are no live generic parameters; a signature
        // is always concrete or polymorphic-erased, so generics reads 0. Recorded
        // as a profile limitation rather than faked.
        generics: 0,
    };
    let type_shape = TypeShape {
        params: params.iter().map(|t| shape_ty(*t, 0)).collect(),
        result: shape_ty(*output, 0),
    };

    let walk = walk_body(body);
    let stmt_histogram = histogram(&walk.node_kinds);
    let shingles = shingles(&walk.node_kinds);
    let token_len = walk.node_kinds.len() as u32;

    Some(Signature {
        symbol_id: symbol_id.clone(),
        display: symbol_id,
        language: "rust".to_string(),
        kind: kind.to_string(),
        file,
        line_start,
        line_end,
        arity,
        cfg: walk.cfg,
        stmt_histogram,
        call_sequence: walk.call_sequence,
        type_shape,
        shingles,
        token_len,
        // MIR is post-expansion: macro-generated logic is already present in the
        // body, so no per-body macro opacity flag is set (the syn caveat is lifted
        // — see the profile). `mir` marks the producing extractor for the record.
        features: BTreeMap::from([("mir".to_string(), "true".to_string())]),
    })
}

/// Whether a resolved type is the unit tuple `()`.
fn is_unit(ty: Ty) -> bool {
    matches!(ty.kind(), TyKind::RigidTy(RigidTy::Tuple(ref ts)) if ts.is_empty())
}

/// The result of walking one MIR body: the node-kind sequence (statements +
/// terminators, bookkeeping dropped) that drives the shingles/histogram, the
/// ordered resolved call sequence, and the best-effort control-flow skeleton.
#[derive(Default)]
struct Walk {
    node_kinds: Vec<String>,
    call_sequence: Vec<String>,
    cfg: Cfg,
}

/// Walk the flat MIR basic blocks in order, tagging each meaningful statement and
/// terminator into the node-kind sequence and reading the control-flow skeleton
/// from terminator structure: `SwitchInt` fan-out (branch vs match arms), CFG
/// back-edges (loops), `Return` terminators (return points), and `Call` unwind.
/// `max_nesting` is not recoverable from flat MIR and stays 0 (see the profile).
fn walk_body(body: &Body) -> Walk {
    let mut w = Walk::default();
    let blocks = &body.blocks;
    for (bidx, block) in blocks.iter().enumerate() {
        for stmt in &block.statements {
            if let Some(tag) = statement_tag(&stmt.kind) {
                w.node_kinds.push(tag.to_string());
            }
        }
        classify_terminator(&block.terminator.kind, bidx, &mut w);
    }
    w
}

/// A short, stable tag for a MIR statement kind — or `None` for pure bookkeeping
/// (`StorageLive`/`StorageDead`/`Nop`/`FakeRead`/`PlaceMention`/`AscribeUserType`/
/// coverage), which is dropped so the fingerprint reflects real work, not the
/// compiler's slot lifetimes.
fn statement_tag(kind: &StatementKind) -> Option<&'static str> {
    match kind {
        StatementKind::Assign(..) => Some("assign"),
        StatementKind::SetDiscriminant { .. } => Some("set_discriminant"),
        StatementKind::Intrinsic(..) => Some("intrinsic"),
        _ => None,
    }
}

/// Read a terminator into the node-kind sequence, the call sequence, and the CFG
/// skeleton. `bidx` is the current block index, used for back-edge (loop)
/// detection: a successor block at index `<= bidx` is a back-edge.
fn classify_terminator(kind: &TerminatorKind, bidx: usize, w: &mut Walk) {
    match kind {
        TerminatorKind::SwitchInt { targets, .. } => {
            w.node_kinds.push("switch".to_string());
            // A boolean `if` lowers to a SwitchInt with a single explicit value +
            // otherwise; a `match` fans out to several. Best-effort: <=1 explicit
            // branch reads as a branch point, more as match arms.
            let explicit = switch_branch_count(targets);
            if explicit <= 1 {
                w.cfg.branch_count += 1;
            } else {
                w.cfg.match_arms += explicit + 1;
            }
            for t in switch_all_targets(targets) {
                back_edge(t, bidx, w);
            }
        }
        TerminatorKind::Return => {
            w.node_kinds.push("return".to_string());
            w.cfg.return_points += 1;
        }
        TerminatorKind::Call {
            func, target, ..
        } => {
            w.node_kinds.push("call".to_string());
            record_call(func, w);
            if let Some(t) = target {
                back_edge(*t, bidx, w);
            }
        }
        TerminatorKind::Drop { target, .. } => {
            w.node_kinds.push("drop".to_string());
            back_edge(*target, bidx, w);
        }
        TerminatorKind::Assert { target, .. } => {
            w.node_kinds.push("assert".to_string());
            back_edge(*target, bidx, w);
        }
        TerminatorKind::Goto { target } => {
            // A goto is a pure control edge, not real work — kept out of the
            // fingerprint, but its target still counts for loop detection.
            back_edge(*target, bidx, w);
        }
        TerminatorKind::InlineAsm { .. } => w.node_kinds.push("asm".to_string()),
        TerminatorKind::Unreachable => w.node_kinds.push("unreachable".to_string()),
        // Resume / Abort (unwind paths): bookkeeping, dropped.
        _ => {}
    }
}

/// Count a back-edge (successor block index `<= bidx`) as one loop.
fn back_edge(target: usize, bidx: usize, w: &mut Walk) {
    if target <= bidx {
        w.cfg.loop_count += 1;
    }
}

/// The number of explicit (non-`otherwise`) branches of a `SwitchInt`.
fn switch_branch_count(targets: &SwitchTargets) -> u32 {
    targets.branches().count() as u32
}

/// Every successor block of a `SwitchInt` (explicit branches + the otherwise
/// arm), for back-edge detection.
fn switch_all_targets(targets: &SwitchTargets) -> Vec<usize> {
    let mut out: Vec<usize> = targets.branches().map(|(_, b)| b).collect();
    out.push(targets.otherwise());
    out
}

/// Record a `Call` terminator's callee into the ordered call sequence and count
/// `?`-operator try points. A statically named callee (`FnDef`) resolves through
/// the driver's `fndef_name` (the same resolution the effect path uses); an
/// indirect (fn-pointer / `dyn`) callee has no name and is skipped — the honest
/// dynamic-dispatch gap, surfaced not faked.
fn record_call(func: &rustc_public::mir::Operand, w: &mut Walk) {
    // The func operand's type tells us the callee. We only have the operand, not
    // the body's locals here, so read the constant fn type directly.
    if let rustc_public::mir::Operand::Constant(c) = func {
        if let TyKind::RigidTy(RigidTy::FnDef(def, args)) = c.ty().kind() {
            let full = fndef_name(def, &args);
            // The `?` operator lowers to a resolved `Try::branch` call; count it as
            // a try point (the syn `?`-count analogue, read from lowered MIR).
            if strip_generics(&full).contains("Try::branch") {
                w.cfg.try_count += 1;
            }
            w.call_sequence.push(simple_callee(&full));
            return;
        }
    }
    // Indirect / unresolved callee — not named, not counted.
}

/// The callee's simple name: generics stripped, last non-empty path segment.
fn simple_callee(full: &str) -> String {
    let stripped = strip_generics(full);
    stripped
        .split("::")
        .filter(|s| !s.is_empty())
        .last()
        .unwrap_or(&stripped)
        .trim()
        .to_string()
}

/// Reduce a resolved type to its structural shape, erasing leaf/parameter
/// identities to `_` while keeping constructors — the MIR analogue of the syn
/// extractor's `type_shape_str`, so `Vec<Foo>` → `Vec<_>`, `Result<T,E>` →
/// `Result<_,_>`, `&str` → `&_`, and a bare nominal or type parameter → `_`.
/// Recursion is bounded by a depth guard against pathological recursive types.
fn shape_ty(ty: Ty, depth: u32) -> String {
    if depth > 16 {
        return "_".to_string();
    }
    match ty.kind() {
        TyKind::RigidTy(rigid) => shape_rigid(rigid, depth),
        // Type parameters / projections / aliases that survived erasure: a leaf.
        _ => "_".to_string(),
    }
}

/// The shape of a resolved rigid type.
fn shape_rigid(rigid: RigidTy, depth: u32) -> String {
    match rigid {
        // Primitive leaves erase to `_`, exactly like a bare nominal.
        RigidTy::Bool
        | RigidTy::Char
        | RigidTy::Int(_)
        | RigidTy::Uint(_)
        | RigidTy::Float(_)
        | RigidTy::Str
        | RigidTy::Foreign(_) => "_".to_string(),
        RigidTy::Adt(adt, args) => {
            let inner: Vec<String> = args
                .0
                .iter()
                .filter_map(|a| match a {
                    GenericArgKind::Type(t) => Some(shape_ty(*t, depth + 1)),
                    _ => None,
                })
                .collect();
            if inner.is_empty() {
                // A bare nominal (no type arguments) is a leaf identifier → `_`,
                // matching the syn extractor.
                "_".to_string()
            } else {
                format!("{}<{}>", adt_simple_name(&adt.name()), inner.join(","))
            }
        }
        RigidTy::Ref(_, inner, _) => format!("&{}", shape_ty(inner, depth + 1)),
        RigidTy::RawPtr(inner, _) => format!("*{}", shape_ty(inner, depth + 1)),
        RigidTy::Slice(inner) => format!("[{}]", shape_ty(inner, depth + 1)),
        RigidTy::Array(inner, _) => format!("[{};_]", shape_ty(inner, depth + 1)),
        RigidTy::Tuple(inners) => {
            if inners.is_empty() {
                "()".to_string()
            } else {
                let parts: Vec<String> = inners.iter().map(|t| shape_ty(*t, depth + 1)).collect();
                format!("({})", parts.join(","))
            }
        }
        RigidTy::FnDef(..) | RigidTy::FnPtr(_) => "fn(_)".to_string(),
        RigidTy::Dynamic(..) => "dyn _".to_string(),
        RigidTy::Never => "!".to_string(),
        RigidTy::Closure(..) => "closure".to_string(),
        RigidTy::Coroutine(..) => "coroutine".to_string(),
        _ => "_".to_string(),
    }
}

/// The last path segment of an ADT's (generics-free) name — the constructor.
fn adt_simple_name(name: &str) -> String {
    name.split("::")
        .filter(|s| !s.is_empty())
        .last()
        .unwrap_or(name)
        .to_string()
}

/// Node-kind counts over the visited sequence.
fn histogram(kinds: &[String]) -> BTreeMap<String, u32> {
    let mut h = BTreeMap::new();
    for k in kinds {
        *h.entry(k.clone()).or_insert(0) += 1;
    }
    h
}

/// k-gram (k = [`SHINGLE_K`]) FNV-1a hashes over the node-kind sequence, masked to
/// 53 bits so each serializes as a JSON-safe integer the engine's `u64` accepts —
/// matching the TypeScript extractor's `fnv1a53`. A sequence shorter than k yields
/// one shingle over the whole sequence.
fn shingles(kinds: &[String]) -> Vec<u64> {
    if kinds.is_empty() {
        return Vec::new();
    }
    if kinds.len() < SHINGLE_K {
        return vec![fnv1a53(&kinds.join("|"))];
    }
    kinds
        .windows(SHINGLE_K)
        .map(|w| fnv1a53(&w.join("|")))
        .collect()
}

/// FNV-1a over a string, masked to 53 bits (a safe JSON integer).
fn fnv1a53(s: &str) -> u64 {
    const SAFE53_MASK: u64 = 0x1f_ffff_ffff_ffff;
    let mut hash: u64 = 0xCBF2_9CE4_8422_2325;
    for b in s.as_bytes() {
        hash ^= *b as u64;
        hash = hash.wrapping_mul(0x100_0000_01B3);
    }
    hash & SAFE53_MASK
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The pure formatting seam of the type-shape walker: a constructor keeps its
    /// simple name with erased leaf args, so aliases/instantiations of the same
    /// constructor collapse to one shape — exercisable without a compiler context.
    #[test]
    fn adt_simple_name_is_the_last_segment() {
        assert_eq!(adt_simple_name("std::vec::Vec"), "Vec");
        assert_eq!(adt_simple_name("std::collections::HashMap"), "HashMap");
        assert_eq!(adt_simple_name("Widget"), "Widget");
        assert_eq!(adt_simple_name("std::string::String"), "String");
    }

    /// A callee's simple name drops generics and path, and tolerates the trailing
    /// `::` `strip_generics` can leave.
    #[test]
    fn simple_callee_strips_generics_and_path() {
        assert_eq!(simple_callee("std::fs::read_to_string::<&str>"), "read_to_string");
        assert_eq!(simple_callee("std::ops::Try::branch"), "branch");
        assert_eq!(simple_callee("core::cmp::max::<usize>"), "max");
    }

    /// Shingle hashes fit in 53 bits (JSON-safe) and a short sequence still
    /// fingerprints as a single shingle.
    #[test]
    fn shingles_are_53_bit_safe() {
        let seq: Vec<String> = ["assign", "call", "switch", "return"]
            .iter()
            .map(|s| s.to_string())
            .collect();
        let sh = shingles(&seq);
        assert_eq!(sh.len(), 2); // windows of 3 over 4 → 2
        assert!(sh.iter().all(|h| *h <= 0x1f_ffff_ffff_ffff));
        let short: Vec<String> = vec!["assign".to_string()];
        assert_eq!(shingles(&short).len(), 1);
    }
}
