//! Lower the language-agnostic [`body`](super::body) IR into a **Quint model
//! skeleton** — a `hinzu model --emit quint` document builder.
//!
//! This is Phase A of the code-derived formal-verification pipeline: it turns
//! the extracted control-flow-graph facts into something a model checker can
//! consume. It is deliberately a *skeleton*, not a finished model. Everything it
//! can lower faithfully — state variables typed by numeric kind, straight-line
//! statement assignments, arithmetic and comparison operators — it emits as real
//! Quint inside clearly-delimited `BEGIN GENERATED` / `END GENERATED` regions.
//! Everything that needs a human (or agent) judgment call — a float abstraction,
//! a control-flow encoding, environment nondeterminism, the actual invariants —
//! is emitted as an explicit `// AGENT-TODO` hole, never as a faked value.
//!
//! Because the holes are `//` comments, the emitted document parses as valid
//! Quint as-is. See `notes/model-finishing.md` for how to fill the holes.
//!
//! Purity: like the rest of `hinzu-core`, this module does string building only —
//! no filesystem, network, environment, clock, or process access. The CLI side
//! owns the I/O (reading the body facts, writing the `.qnt` file). Determinism:
//! functions are visited in `facts.functions` order, locals by index, blocks by
//! index; there are no timestamps or randomness.

use super::body::{
    BinOp, Block, BodyFacts, ConstVal, FunctionBody, NumKind, Operand, Rvalue, Terminator, UnOp,
};

/// Lower a whole body-fact set into a single Quint `module derived { ... }`
/// skeleton string. Pure: allocates the output string and nothing else.
pub fn emit_quint(facts: &BodyFacts) -> String {
    let mut out = String::new();
    emit_header(&mut out, facts);
    emit_state_vars(&mut out, facts);
    for func in &facts.functions {
        emit_action(&mut out, func);
    }
    emit_init(&mut out, facts);
    emit_step(&mut out, facts);
    emit_invariants(&mut out);
    out.push_str("}\n");
    out
}

/// The module header: a provenance comment explaining what generated the file
/// and how to finish it, then the `module derived {` opener.
fn emit_header(out: &mut String, facts: &BodyFacts) {
    out.push_str("// Generated by `hinzu model --emit quint` — do NOT hand-edit the\n");
    out.push_str("// `BEGIN GENERATED` / `END GENERATED` regions; regenerate them from the body\n");
    out.push_str("// IR instead. Fill the `// AGENT-TODO` holes to finish the model; see\n");
    out.push_str("// notes/model-finishing.md for what each hole is asking for.\n");
    out.push_str("//\n");
    out.push_str(&format!(
        "// Lowered from {} function bod{}.\n",
        facts.functions.len(),
        if facts.functions.len() == 1 {
            "y"
        } else {
            "ies"
        }
    ));
    out.push_str("module derived {\n");
}

/// The module-level `var` declarations: one per local of every function, typed
/// by numeric kind, named with a per-function key so no two functions collide.
fn emit_state_vars(out: &mut String, facts: &BodyFacts) {
    out.push_str("\n  // ---- BEGIN GENERATED: state vars ----\n");
    if facts.functions.is_empty() {
        out.push_str("  // (no functions in the body facts — nothing to declare)\n");
    }
    for func in &facts.functions {
        let key = fn_key(&func.id);
        for (idx, local) in func.locals.iter().enumerate() {
            let (ty, todo) = quint_type(local.kind);
            let role = local_role(idx, func.arg_count);
            out.push_str(&format!(
                "  var {name}: {ty} // {role} of {display} ({file}:{line}){todo}\n",
                name = var_name(&key, idx),
                ty = ty,
                role = role,
                display = func.display,
                file = func.file,
                line = func.line,
                todo = todo,
            ));
        }
    }
    out.push_str("  // ---- END GENERATED ----\n");
}

/// One rendered line of an action body: a standalone comment, a blank spacer, or
/// an action expression carrying an optional trailing inline comment. Modeling
/// them lets the renderer put the `all {}` separator comma *after* the
/// expression but *before* the inline comment, so a `// ...` never swallows it.
enum Line {
    Blank,
    Comment(String),
    Expr { expr: String, note: Option<String> },
}

/// One `action <fnkey> = all { ... }` per function. Straight-line statements of
/// the entry block lower to real Quint assignments; anything the skeleton cannot
/// lower faithfully becomes an `// AGENT-TODO` hole.
fn emit_action(out: &mut String, func: &FunctionBody) {
    let key = fn_key(&func.id);
    out.push_str(&format!(
        "\n  // ---- action {key} (derived from {id} @ {file}:{line}) ----\n",
        key = key,
        id = func.id,
        file = func.file,
        line = func.line,
    ));
    out.push_str(&format!("  action {key} = all {{\n"));

    let mut lines: Vec<Line> = Vec::new();

    // Lower the straight-line statements of the entry block (block 0), which is
    // always present for a non-degenerate body. This is the real derived
    // content — it holds regardless of the control-flow shape.
    if let Some(entry) = func.blocks.first() {
        lower_block_stmts(&key, entry, &mut lines);
    }

    // Control flow: a single Return-terminated block lowers directly; anything
    // richer (multiple blocks, a SwitchInt, a back-edge, an Assert or a Call
    // with a continuation) is surfaced as a CFG summary + a hole rather than an
    // invented program-counter machine.
    if !is_straight_line(func) {
        lines.push(Line::Blank);
        lines.push(Line::Comment(format!(
            "---- CFG ({} blocks) ----",
            func.blocks.len()
        )));
        for (bidx, block) in func.blocks.iter().enumerate() {
            lines.push(Line::Comment(format!(
                "block {bidx}: {}",
                describe_terminator(&block.terminator)
            )));
        }
        lines.push(Line::Comment(
            "AGENT-TODO: encode control flow — this CFG needs a state-abstraction \
             choice (see notes/model-finishing.md)"
                .to_string(),
        ));
    }

    // An action body must contain at least one action expression to parse; if
    // all we have are comments, add a no-op so the `all { ... }` is well-formed.
    let has_expr = lines.iter().any(|l| matches!(l, Line::Expr { .. }));
    if !has_expr {
        lines.push(Line::Expr {
            expr: "true".to_string(),
            note: Some("AGENT-TODO: this action has no derived assignments".to_string()),
        });
    }

    render_action_lines(out, &lines);
    out.push_str("  }\n");
}

/// Render an action body's lines into `out`. Every expression gets the `all {}`
/// separator comma (a trailing comma before `}` is legal Quint), placed before
/// any inline comment so the comment cannot eat it.
fn render_action_lines(out: &mut String, lines: &[Line]) {
    for line in lines {
        match line {
            Line::Blank => out.push('\n'),
            Line::Comment(c) => out.push_str(&format!("    // {c}\n")),
            Line::Expr { expr, note } => match note {
                Some(n) => out.push_str(&format!("    {expr}, // {n}\n")),
                None => out.push_str(&format!("    {expr},\n")),
            },
        }
    }
}

/// Lower the straight-line assignment statements of one block into action lines,
/// appending them to `lines`.
fn lower_block_stmts(key: &str, block: &Block, lines: &mut Vec<Line>) {
    for stmt in &block.stmts {
        let place = var_name(key, stmt.place as usize);
        match &stmt.rvalue {
            Rvalue::Use { operand } => lines.push(Line::Expr {
                expr: format!("{place}' = {}", lower_operand(key, operand)),
                note: None,
            }),
            Rvalue::Binary { kind, left, right } => match quint_binop(*kind) {
                Some(op) => lines.push(Line::Expr {
                    expr: format!(
                        "{place}' = {l} {op} {r}",
                        l = lower_operand(key, left),
                        op = op,
                        r = lower_operand(key, right),
                    ),
                    note: None,
                }),
                None => push_nondet_hole(
                    lines,
                    &place,
                    format!("unsupported binop for {place} — choose an encoding"),
                ),
            },
            Rvalue::Unary { kind, operand } => {
                let inner = lower_operand(key, operand);
                match kind {
                    UnOp::Neg => lines.push(Line::Expr {
                        expr: format!("{place}' = -({inner})"),
                        note: None,
                    }),
                    UnOp::Not => lines.push(Line::Expr {
                        expr: format!("{place}' = not({inner})"),
                        note: None,
                    }),
                    UnOp::Other => push_nondet_hole(
                        lines,
                        &place,
                        format!("unsupported unary op for {place} — choose an encoding"),
                    ),
                }
            }
            Rvalue::Unknown => push_nondet_hole(
                lines,
                &place,
                format!("environment nondeterminism — {place}' = <choose a value>"),
            ),
        }
    }
}

/// Push an `// AGENT-TODO` comment plus a keep-the-current-value nondet
/// placeholder assignment, the shape every un-lowerable rvalue takes.
fn push_nondet_hole(lines: &mut Vec<Line>, place: &str, reason: String) {
    lines.push(Line::Comment(format!("AGENT-TODO: {reason}")));
    lines.push(Line::Expr {
        expr: format!("{place}' = {place}"),
        note: Some("AGENT-TODO: nondet hole".to_string()),
    });
}

/// Lower an operand to a Quint expression: a local read to its var name, a
/// modelable constant to its literal, an unmodelable constant to a placeholder.
fn lower_operand(key: &str, operand: &Operand) -> String {
    match operand {
        Operand::Local { local } => var_name(key, *local as usize),
        Operand::Const { value } => match value {
            ConstVal::Int(v) => v.to_string(),
            ConstVal::Uint(v) => v.to_string(),
            ConstVal::Bool(v) => v.to_string(),
            ConstVal::Float(_) => {
                "0 /* AGENT-TODO: float constant — choose an abstraction */".to_string()
            }
            ConstVal::Unknown => {
                "0 /* AGENT-TODO: unknown constant — choose a value */".to_string()
            }
        },
    }
}

/// The generated `init` action: every var set to a typed zero value, each with a
/// hole asking for the real initial state.
fn emit_init(out: &mut String, facts: &BodyFacts) {
    out.push_str("\n  // ---- BEGIN GENERATED: init ----\n");
    out.push_str("  action init = all {\n");
    let mut any = false;
    for func in &facts.functions {
        let key = fn_key(&func.id);
        for (idx, local) in func.locals.iter().enumerate() {
            any = true;
            let zero = match local.kind {
                NumKind::Bool => "false",
                _ => "0",
            };
            out.push_str(&format!(
                "    {name}' = {zero}, // AGENT-TODO: choose real initial state\n",
                name = var_name(&key, idx),
                zero = zero,
            ));
        }
    }
    if !any {
        out.push_str("    true, // AGENT-TODO: no state to initialize\n");
    }
    out.push_str("  }\n");
    out.push_str("  // ---- END GENERATED ----\n");
}

/// The generated `step` action: a nondeterministic choice over the per-function
/// actions, with a hole for the environment actions the model still needs.
fn emit_step(out: &mut String, facts: &BodyFacts) {
    out.push_str("\n  // ---- BEGIN GENERATED: step ----\n");
    out.push_str("  action step = any {\n");
    if facts.functions.is_empty() {
        out.push_str("    true, // AGENT-TODO: no function actions to choose from\n");
    }
    for func in &facts.functions {
        out.push_str(&format!("    {},\n", fn_key(&func.id)));
    }
    out.push_str("    // AGENT-TODO: add environment actions (message loss, races, aborts)\n");
    out.push_str("  }\n");
    out.push_str("  // ---- END GENERATED ----\n");
}

/// The generated invariants region: a commented example plus a hole for the
/// real state invariants.
fn emit_invariants(out: &mut String) {
    out.push_str("\n  // ---- BEGIN GENERATED: invariants ----\n");
    out.push_str("  // AGENT-TODO: state invariants — the properties the model should prove.\n");
    out.push_str("  // val exampleInv = true\n");
    out.push_str("  // ---- END GENERATED ----\n");
}

// ---- helpers -------------------------------------------------------------

/// A sanitized, collision-free variable-name stem for a function: every
/// non-alphanumeric character of its symbol id becomes `_`.
fn fn_key(id: &str) -> String {
    id.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

/// The module-level var name for local `idx` of the function keyed `key`.
fn var_name(key: &str, idx: usize) -> String {
    format!("{key}_l{idx}")
}

/// The Quint type for a numeric kind, plus any trailing `// AGENT-TODO` the
/// abstraction choice needs. Int/Uint map to `int`; Bool to `bool`; Float to
/// `int` with a float-abstraction hole; Other to `int` with an unknown-type
/// hole.
fn quint_type(kind: NumKind) -> (&'static str, &'static str) {
    match kind {
        NumKind::Int | NumKind::Uint => ("int", ""),
        NumKind::Bool => ("bool", ""),
        NumKind::Float => (
            "int",
            " // AGENT-TODO: Quint has no floats — choose an abstraction",
        ),
        NumKind::Other => ("int", " // AGENT-TODO: unknown type — choose abstraction"),
    }
}

/// How local `idx` is used: the return place (0), a parameter (`1..=arg_count`),
/// or a temporary.
fn local_role(idx: usize, arg_count: usize) -> &'static str {
    if idx == 0 {
        "return place"
    } else if idx <= arg_count {
        "param"
    } else {
        "temp"
    }
}

/// The Quint operator for a modeled binary op, or `None` for `Other` (which
/// becomes a hole).
fn quint_binop(kind: BinOp) -> Option<&'static str> {
    Some(match kind {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Rem => "%",
        BinOp::Eq => "==",
        BinOp::Ne => "!=",
        BinOp::Lt => "<",
        BinOp::Le => "<=",
        BinOp::Gt => ">",
        BinOp::Ge => ">=",
        BinOp::Other => return None,
    })
}

/// Whether a function is a single block ending in `Return` — the case that
/// lowers directly, with no CFG hole.
fn is_straight_line(func: &FunctionBody) -> bool {
    func.blocks.len() == 1 && matches!(func.blocks[0].terminator, Terminator::Return)
}

/// A one-line human description of a terminator for the CFG summary comment.
fn describe_terminator(term: &Terminator) -> String {
    match term {
        Terminator::Goto { block } => format!("Goto -> block {block}"),
        Terminator::Return => "Return".to_string(),
        Terminator::Unreachable => "Unreachable".to_string(),
        Terminator::SwitchInt {
            targets, otherwise, ..
        } => {
            let mut cases: Vec<String> = targets
                .iter()
                .map(|t| format!("{}=>{}", t.value, t.block))
                .collect();
            if let Some(o) = otherwise {
                cases.push(format!("else=>{o}"));
            }
            format!("SwitchInt [{}]", cases.join(", "))
        }
        Terminator::Assert { target } => format!("Assert -> block {target}"),
        Terminator::Call {
            destination,
            target,
        } => {
            let dest = destination
                .map(|d| format!("dest _{d}"))
                .unwrap_or_else(|| "no dest".to_string());
            let tgt = target
                .map(|t| format!("-> block {t}"))
                .unwrap_or_else(|| "diverging".to_string());
            format!("Call ({dest}) {tgt}")
        }
        Terminator::Other { successors } => {
            let succ: Vec<String> = successors.iter().map(|s| s.to_string()).collect();
            format!("Other -> [{}]", succ.join(", "))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::super::body::*;
    use super::*;

    /// A one-block `id(a, b) { _0 = a <op> b; return }` over two integer params
    /// plus the return place — the straight-line shape the emitter lowers
    /// directly.
    fn binop_fn(id: &str, op: BinOp) -> FunctionBody {
        FunctionBody {
            id: id.into(),
            display: id.into(),
            file: "demo.rs".into(),
            line: 1,
            arg_count: 2,
            locals: vec![
                Local { kind: NumKind::Int },
                Local { kind: NumKind::Int },
                Local { kind: NumKind::Int },
            ],
            blocks: vec![Block {
                stmts: vec![Stmt {
                    place: 0,
                    rvalue: Rvalue::Binary {
                        kind: op,
                        left: Operand::Local { local: 1 },
                        right: Operand::Local { local: 2 },
                    },
                    loc: Loc::default(),
                }],
                terminator: Terminator::Return,
            }],
        }
    }

    #[test]
    fn emits_module_header_and_generated_markers() {
        let facts = BodyFacts {
            functions: vec![binop_fn("app::ratio", BinOp::Div)],
        };
        let out = emit_quint(&facts);
        assert!(out.contains("module derived"), "missing module header");
        assert!(
            out.contains("// ---- BEGIN GENERATED: state vars ----"),
            "missing state-var region marker"
        );
        assert!(
            out.contains("// ---- END GENERATED ----"),
            "missing END GENERATED marker"
        );
    }

    #[test]
    fn declares_a_typed_state_var_for_a_known_local() {
        let facts = BodyFacts {
            functions: vec![binop_fn("app::ratio", BinOp::Div)],
        };
        let out = emit_quint(&facts);
        // local 1 is the first param, typed int, named <key>_l1.
        assert!(
            out.contains("var app__ratio_l1: int"),
            "missing typed state var for local 1;\n{out}"
        );
        assert!(out.contains("param"), "local role annotation missing");
    }

    #[test]
    fn emits_one_action_per_function_and_lowers_div_to_slash() {
        let facts = BodyFacts {
            functions: vec![
                binop_fn("app::ratio", BinOp::Div),
                binop_fn("app::sum", BinOp::Add),
            ],
        };
        let out = emit_quint(&facts);
        assert!(
            out.contains("action app__ratio = all {"),
            "missing ratio action"
        );
        assert!(
            out.contains("action app__sum = all {"),
            "missing sum action"
        );
        // div lowers to `/`.
        assert!(
            out.contains("app__ratio_l0' = app__ratio_l1 / app__ratio_l2"),
            "div not lowered to `/`;\n{out}"
        );
    }

    #[test]
    fn unknown_rvalue_becomes_an_agent_todo_hole() {
        let f = FunctionBody {
            id: "app::env".into(),
            display: "env".into(),
            file: "demo.rs".into(),
            line: 1,
            arg_count: 0,
            locals: vec![Local { kind: NumKind::Int }],
            blocks: vec![Block {
                stmts: vec![Stmt {
                    place: 0,
                    rvalue: Rvalue::Unknown,
                    loc: Loc::default(),
                }],
                terminator: Terminator::Return,
            }],
        };
        let out = emit_quint(&BodyFacts { functions: vec![f] });
        assert!(
            out.contains("AGENT-TODO: environment nondeterminism"),
            "Unknown rvalue should surface an AGENT-TODO hole;\n{out}"
        );
    }

    #[test]
    fn a_float_local_gets_a_float_abstraction_hole() {
        let f = FunctionBody {
            id: "app::f".into(),
            display: "f".into(),
            file: "demo.rs".into(),
            line: 1,
            arg_count: 0,
            locals: vec![Local {
                kind: NumKind::Float,
            }],
            blocks: vec![Block {
                stmts: vec![],
                terminator: Terminator::Return,
            }],
        };
        let out = emit_quint(&BodyFacts { functions: vec![f] });
        assert!(
            out.contains("Quint has no floats"),
            "float local should carry a float-abstraction hole;\n{out}"
        );
    }

    #[test]
    fn a_multi_block_switchint_surfaces_a_cfg_hole() {
        // Two blocks, entry ends in a SwitchInt — not straight-line, so a CFG
        // summary + hole is emitted while block 0's stmts still lower.
        let f = FunctionBody {
            id: "app::guarded".into(),
            display: "guarded".into(),
            file: "demo.rs".into(),
            line: 1,
            arg_count: 1,
            locals: vec![
                Local { kind: NumKind::Int },
                Local { kind: NumKind::Int },
                Local {
                    kind: NumKind::Bool,
                },
            ],
            blocks: vec![
                Block {
                    stmts: vec![Stmt {
                        place: 2,
                        rvalue: Rvalue::Binary {
                            kind: BinOp::Ne,
                            left: Operand::Local { local: 1 },
                            right: Operand::Const {
                                value: ConstVal::Int(0),
                            },
                        },
                        loc: Loc::default(),
                    }],
                    terminator: Terminator::SwitchInt {
                        discr: Operand::Local { local: 2 },
                        targets: vec![SwitchTarget { value: 0, block: 1 }],
                        otherwise: None,
                    },
                },
                Block {
                    stmts: vec![],
                    terminator: Terminator::Return,
                },
            ],
        };
        let out = emit_quint(&BodyFacts { functions: vec![f] });
        assert!(
            out.contains("// ---- CFG (2 blocks) ----"),
            "multi-block body should surface a CFG summary;\n{out}"
        );
        assert!(
            out.contains("AGENT-TODO: encode control flow"),
            "CFG should carry a control-flow hole;\n{out}"
        );
        assert!(
            out.contains("SwitchInt"),
            "the SwitchInt terminator should appear in the CFG summary;\n{out}"
        );
        // Block 0's comparison still lowers to real derived content.
        assert!(
            out.contains("app__guarded_l2' = app__guarded_l1 != 0"),
            "block 0's straight-line stmt should still lower;\n{out}"
        );
    }
}
