//! Lower the language-agnostic [`body`](super::body) IR into a **Stateright model
//! skeleton** — a `hinzu model --emit stateright` document builder.
//!
//! This is Phase D of the code-derived formal-verification pipeline: the same
//! extracted control-flow-graph facts Phase A lowers to Quint are lowered here to
//! a Rust module implementing [Stateright](https://docs.rs/stateright)'s `Model`
//! trait. Like the Quint emitter it is deliberately a *skeleton*, not a finished
//! model. Everything it can lower faithfully — a `DerivedState` struct whose
//! fields are the functions' locals typed by numeric kind, a `DerivedAction` enum
//! with one variant per function, and each function's entry-block straight-line
//! statements lowered to real Rust state mutations inside a `next_state` match —
//! it emits as real Rust inside clearly-delimited `BEGIN GENERATED` /
//! `END GENERATED` regions. Everything that needs a human (or agent) judgment
//! call — a float abstraction, a control-flow encoding, the real initial state,
//! which actions are enabled, environment nondeterminism, the invariants — is
//! emitted as an explicit `// AGENT-TODO` hole, never as a faked value.
//!
//! Because the holes are `//` comments, every emitted region is valid Rust as-is
//! (the finished model additionally needs the `stateright` crate as a dependency
//! and a real pidgin type wrapped in `DerivedModel`). See `notes/model-finishing.md`.
//!
//! Purity: like the rest of `hinzu-core`, this module does string building only —
//! no filesystem, network, environment, clock, or process access. The CLI side
//! owns the I/O (reading the body facts, writing the `.rs` file). Determinism:
//! functions are visited in `facts.functions` order, locals by index, blocks by
//! index; there are no timestamps or randomness.

use super::body::{BodyFacts, FunctionBody, NumKind, Operand, Rvalue, UnOp};
use super::emit_common::{
    binop_symbol, describe_terminator, fn_key, is_straight_line, local_role, lower_const, var_name,
};

/// Lower a whole body-fact set into a single Stateright model module string
/// (a `.rs` file's worth of source). Pure: allocates the output string and
/// nothing else.
pub fn emit_stateright(facts: &BodyFacts) -> String {
    let mut out = String::new();
    emit_header(&mut out, facts);
    emit_state_struct(&mut out, facts);
    emit_action_enum(&mut out, facts);
    emit_model(&mut out, facts);
    out
}

/// The module header: a provenance comment explaining what generated the file and
/// how to finish it, then the `use stateright::*;` import (with the note that
/// finishing requires adding the crate).
fn emit_header(out: &mut String, facts: &BodyFacts) {
    let n = facts.functions.len();
    out.push_str("// Generated by `hinzu model --emit stateright` — do NOT hand-edit the\n");
    out.push_str("// `BEGIN GENERATED` / `END GENERATED` regions; regenerate them from the body\n");
    out.push_str("// IR instead. Fill the `// AGENT-TODO` holes to finish the model; see\n");
    out.push_str("// notes/model-finishing.md for what each hole is asking for.\n");
    out.push_str("//\n");
    out.push_str(&format!(
        "// This module represents {n} extracted function bod{} as a Stateright `Model`:\n",
        if n == 1 { "y" } else { "ies" }
    ));
    out.push_str("// `DerivedState` carries their locals, `DerivedAction` picks a function, and\n");
    out.push_str("// `next_state` lowers each function's entry-block statements to state\n");
    out.push_str(
        "// mutations. Finishing it means wrapping a real pidgin type in `DerivedModel`.\n",
    );
    out.push_str("//\n");
    out.push_str("// Finishing requires adding the `stateright` crate as a dependency.\n");
    out.push_str("use stateright::*;\n");
}

/// The generated `DerivedState` struct: one field per local of every function,
/// typed by numeric kind, named `<fnkey>_l<localid>` with a source comment.
fn emit_state_struct(out: &mut String, facts: &BodyFacts) {
    out.push_str("\n// ---- BEGIN GENERATED: state ----\n");
    out.push_str("#[derive(Clone, Debug, PartialEq, Hash)]\n");
    // Field names are `<fnkey>_l<idx>` where `<fnkey>` may contain `__` (from a
    // `::` in the symbol id), which trips the non_snake_case lint; allow it so the
    // finished model compiles clean.
    out.push_str("#[allow(non_snake_case)]\n");
    out.push_str("pub struct DerivedState {\n");
    if facts.functions.is_empty() {
        out.push_str("    // (no functions in the body facts — nothing to model)\n");
    }
    for func in &facts.functions {
        let key = fn_key(&func.id);
        for (idx, local) in func.locals.iter().enumerate() {
            let (ty, ty_note) = rust_type(local.kind);
            out.push_str(&format!(
                "    pub {name}: {ty}, // {role} of {display} ({file}:{line}){ty_note}\n",
                name = var_name(&key, idx),
                role = local_role(idx, func.arg_count),
                display = func.display,
                file = func.file,
                line = func.line,
            ));
        }
    }
    out.push_str("}\n");
    out.push_str("// ---- END GENERATED ----\n");
}

/// The generated `DerivedAction` enum: one variant per function, keyed by the
/// sanitized symbol id (the same stem the state fields use). Carries an
/// `#[allow(non_camel_case_types)]` so the derived-from-symbol variant names do
/// not warn when the finished model is compiled.
fn emit_action_enum(out: &mut String, facts: &BodyFacts) {
    out.push_str("\n// ---- BEGIN GENERATED: actions ----\n");
    out.push_str("#[derive(Clone, Debug, PartialEq, Hash)]\n");
    out.push_str("#[allow(non_camel_case_types)]\n");
    out.push_str("pub enum DerivedAction {\n");
    if facts.functions.is_empty() {
        out.push_str("    // (no functions in the body facts — no actions to take)\n");
    }
    for func in &facts.functions {
        out.push_str(&format!(
            "    {key}, // derived from {id} @ {file}:{line}\n",
            key = fn_key(&func.id),
            id = func.id,
            file = func.file,
            line = func.line,
        ));
    }
    out.push_str("}\n");
    out.push_str("// ---- END GENERATED ----\n");
}

/// The `DerivedModel` struct and its `impl Model` — `init_states`, `actions`,
/// `next_state`, and `properties`, each a generated region with its holes.
fn emit_model(out: &mut String, facts: &BodyFacts) {
    out.push_str("\n// The model handle. AGENT-TODO: wrap a real pidgin type here — see\n");
    out.push_str("// notes/model-finishing.md — so `init_states`/`next_state` can drive it.\n");
    out.push_str("pub struct DerivedModel {\n");
    out.push_str(
        "    // AGENT-TODO: wrap a real pidgin type here (e.g. the BridgeShared registry)\n",
    );
    out.push_str("}\n");

    out.push_str("\nimpl Model for DerivedModel {\n");
    out.push_str("    type State = DerivedState;\n");
    out.push_str("    type Action = DerivedAction;\n");
    emit_init_states(out, facts);
    emit_actions(out, facts);
    emit_next_state(out, facts);
    emit_properties(out);
    out.push_str("}\n");
}

/// The generated `init_states`: one state with every field zero/false, plus a
/// hole for the real initial state.
fn emit_init_states(out: &mut String, facts: &BodyFacts) {
    out.push_str("\n    // ---- BEGIN GENERATED: init_states ----\n");
    out.push_str("    fn init_states(&self) -> Vec<Self::State> {\n");
    out.push_str("        vec![DerivedState {\n");
    for func in &facts.functions {
        let key = fn_key(&func.id);
        for (idx, local) in func.locals.iter().enumerate() {
            let zero = match local.kind {
                NumKind::Bool => "false",
                _ => "0",
            };
            out.push_str(&format!(
                "            {name}: {zero},\n",
                name = var_name(&key, idx),
            ));
        }
    }
    out.push_str("        }]\n");
    out.push_str(
        "        // AGENT-TODO: real initial state (replace the zero/false placeholders)\n",
    );
    out.push_str("    }\n");
    out.push_str("    // ---- END GENERATED ----\n");
}

/// The generated `actions`: push every `DerivedAction` variant, then a hole for
/// enabling guards and the environment actions the model still needs.
fn emit_actions(out: &mut String, facts: &BodyFacts) {
    out.push_str("\n    // ---- BEGIN GENERATED: actions ----\n");
    out.push_str(
        "    fn actions(&self, _state: &Self::State, actions: &mut Vec<Self::Action>) {\n",
    );
    for func in &facts.functions {
        out.push_str(&format!(
            "        actions.push(DerivedAction::{});\n",
            fn_key(&func.id)
        ));
    }
    out.push_str(
        "        // AGENT-TODO: guard which actions are enabled + add environment actions \
         (message loss/races/aborts)\n",
    );
    out.push_str("    }\n");
    out.push_str("    // ---- END GENERATED ----\n");
}

/// The generated `next_state`: a `match action` whose every arm lowers that
/// function's entry-block straight-line statements to real Rust state mutations,
/// and summarizes any richer CFG as a hole rather than an invented state machine.
fn emit_next_state(out: &mut String, facts: &BodyFacts) {
    out.push_str("\n    // ---- BEGIN GENERATED: next_state ----\n");
    out.push_str(
        "    fn next_state(&self, state: &Self::State, action: Self::Action) \
         -> Option<Self::State> {\n",
    );
    out.push_str("        let mut next = state.clone();\n");
    out.push_str("        match action {\n");
    for func in &facts.functions {
        emit_action_arm(out, func);
    }
    out.push_str("        }\n");
    out.push_str("        Some(next)\n");
    out.push_str("    }\n");
    out.push_str("    // ---- END GENERATED ----\n");
}

/// One `DerivedAction::<key> => { ... }` arm: the entry block's statements lowered
/// to `next.<field> = …` mutations, then — when the function is not a single
/// returning block — a CFG summary plus a control-flow hole.
fn emit_action_arm(out: &mut String, func: &FunctionBody) {
    let key = fn_key(&func.id);
    out.push_str(&format!("            DerivedAction::{key} => {{\n"));
    out.push_str(&format!(
        "                // derived from {id} @ {file}:{line}\n",
        id = func.id,
        file = func.file,
        line = func.line,
    ));

    // Lower the straight-line statements of the entry block (block 0) — the real
    // derived content, which holds regardless of the control-flow shape.
    if let Some(entry) = func.blocks.first() {
        for stmt in &entry.stmts {
            lower_stmt(out, &key, stmt);
        }
    }

    // A one-block Return function lowers directly; anything richer is surfaced as
    // a CFG summary + a hole rather than an invented program-counter machine.
    if !is_straight_line(func) {
        out.push_str(&format!(
            "                // ---- CFG ({} blocks) ----\n",
            func.blocks.len()
        ));
        for (bidx, block) in func.blocks.iter().enumerate() {
            out.push_str(&format!(
                "                // block {bidx}: {}\n",
                describe_terminator(&block.terminator)
            ));
        }
        out.push_str(
            "                // AGENT-TODO: encode control flow — this CFG needs a \
             state-abstraction choice (see notes/model-finishing.md)\n",
        );
    }

    out.push_str("            }\n");
}

/// Lower one straight-line assignment statement to a `next.<field> = …;` mutation,
/// or to an `// AGENT-TODO` hole when the rvalue cannot be lowered faithfully.
fn lower_stmt(out: &mut String, key: &str, stmt: &super::body::Stmt) {
    let place = format!("next.{}", var_name(key, stmt.place as usize));
    match &stmt.rvalue {
        Rvalue::Use { operand } => {
            out.push_str(&format!(
                "                {place} = {};\n",
                operand_expr(key, operand)
            ));
        }
        Rvalue::Binary { kind, left, right } => match binop_symbol(*kind) {
            Some(op) => out.push_str(&format!(
                "                {place} = {l} {op} {r};\n",
                l = operand_expr(key, left),
                r = operand_expr(key, right),
            )),
            None => hole(
                out,
                &format!("unsupported binop for {place} — choose an encoding"),
            ),
        },
        Rvalue::Unary { kind, operand } => {
            let inner = operand_expr(key, operand);
            match kind {
                UnOp::Neg => out.push_str(&format!("                {place} = -({inner});\n")),
                UnOp::Not => out.push_str(&format!("                {place} = !({inner});\n")),
                UnOp::Other => hole(
                    out,
                    &format!("unsupported unary op for {place} — choose an encoding"),
                ),
            }
        }
        Rvalue::Unknown => hole(
            out,
            &format!("environment nondeterminism — {place} = <choose a value>"),
        ),
    }
}

/// Push an `// AGENT-TODO` hole line for a statement the skeleton keeps as-is (the
/// cloned `next` already carries the current value). Reasons come pre-formatted.
fn hole(out: &mut String, reason: &str) {
    out.push_str(&format!("                // AGENT-TODO: {reason}\n"));
}

/// Render an operand as a Rust expression: a local read to the mutating copy's
/// field (`next.<var>`, so sequential straight-line reads see earlier writes), a
/// constant to its shared literal rendering.
fn operand_expr(key: &str, operand: &Operand) -> String {
    match operand {
        Operand::Local { local } => format!("next.{}", var_name(key, *local as usize)),
        Operand::Const { value } => lower_const(value),
    }
}

/// The generated `properties`: a hole for the real invariants plus one commented
/// `Property::always` stub.
fn emit_properties(out: &mut String) {
    out.push_str("\n    // ---- BEGIN GENERATED: properties ----\n");
    out.push_str("    fn properties(&self) -> Vec<Property<Self>> {\n");
    out.push_str(
        "        // AGENT-TODO: state invariants — the properties the model should prove.\n",
    );
    out.push_str("        vec![\n");
    out.push_str("            // Property::always(\"example\", |_, _state| true),\n");
    out.push_str("        ]\n");
    out.push_str("    }\n");
    out.push_str("    // ---- END GENERATED ----\n");
}

/// The Rust field type for a numeric kind, plus any trailing `// AGENT-TODO` the
/// abstraction choice needs. Int/Uint/Bool map faithfully; Float and Other map to
/// `i64` with a hole, since the skeleton cannot pick their abstraction honestly.
fn rust_type(kind: NumKind) -> (&'static str, &'static str) {
    // Bool maps to `bool`; every integer-shaped kind to `i64`. Float and Other
    // additionally carry an abstraction hole, since the skeleton cannot pick their
    // representation honestly — Stateright state must be `Hash`, which a real float
    // is not, so it needs a fixed-point / interval encoding the modeler chooses.
    let ty = if matches!(kind, NumKind::Bool) {
        "bool"
    } else {
        "i64"
    };
    let note = match kind {
        NumKind::Float => {
            " // AGENT-TODO: Stateright state must be Hash — floats aren't; choose an abstraction"
        }
        NumKind::Other => " // AGENT-TODO: unknown type — choose an abstraction",
        _ => "",
    };
    (ty, note)
}

#[cfg(test)]
mod tests {
    use super::super::body::*;
    use super::super::test_support as ts;
    use super::*;

    #[test]
    fn emits_model_impl_and_generated_markers() {
        let facts = BodyFacts {
            functions: vec![ts::binop_fn("app::ratio", BinOp::Div)],
        };
        let out = emit_stateright(&facts);
        assert!(
            out.contains("impl Model for DerivedModel"),
            "missing Model impl;\n{out}"
        );
        assert!(
            out.contains("// ---- BEGIN GENERATED: state ----"),
            "missing state region marker;\n{out}"
        );
        assert!(
            out.contains("// ---- END GENERATED ----"),
            "missing END GENERATED marker;\n{out}"
        );
        assert!(
            out.contains("use stateright::*;"),
            "missing the stateright import;\n{out}"
        );
    }

    #[test]
    fn declares_a_typed_state_field_for_a_known_local() {
        let facts = BodyFacts {
            functions: vec![ts::binop_fn("app::ratio", BinOp::Div)],
        };
        let out = emit_stateright(&facts);
        // local 1 is the first param, typed i64, named <key>_l1.
        assert!(
            out.contains("pub app__ratio_l1: i64"),
            "missing typed state field for local 1;\n{out}"
        );
        assert!(
            out.contains("param"),
            "local role annotation missing;\n{out}"
        );
    }

    #[test]
    fn emits_a_derived_action_variant_per_function() {
        let facts = BodyFacts {
            functions: vec![
                ts::binop_fn("app::ratio", BinOp::Div),
                ts::binop_fn("app::sum", BinOp::Add),
            ],
        };
        let out = emit_stateright(&facts);
        assert!(
            out.contains("enum DerivedAction"),
            "missing action enum;\n{out}"
        );
        assert!(
            out.contains("    app__ratio, //"),
            "missing ratio variant;\n{out}"
        );
        assert!(
            out.contains("    app__sum, //"),
            "missing sum variant;\n{out}"
        );
        // The actions() method pushes each variant.
        assert!(
            out.contains("actions.push(DerivedAction::app__ratio);"),
            "actions() should push the ratio variant;\n{out}"
        );
    }

    #[test]
    fn lowers_a_div_to_a_slash_state_mutation() {
        // A straight-line divide lowers to a real `next.<place> = <l> / <r>;`
        // mutation in the match arm.
        let facts = BodyFacts {
            functions: vec![ts::binop_fn("app::ratio", BinOp::Div)],
        };
        let out = emit_stateright(&facts);
        assert!(
            out.contains("DerivedAction::app__ratio => {"),
            "missing ratio match arm;\n{out}"
        );
        assert!(
            out.contains("next.app__ratio_l0 = next.app__ratio_l1 / next.app__ratio_l2;"),
            "div should lower to a `/` state mutation;\n{out}"
        );
    }

    #[test]
    fn unknown_rvalue_becomes_an_agent_todo_hole() {
        let out = emit_stateright(&BodyFacts {
            functions: vec![ts::unknown_rvalue_fn()],
        });
        assert!(
            out.contains("AGENT-TODO: environment nondeterminism"),
            "Unknown rvalue should surface an AGENT-TODO hole;\n{out}"
        );
    }

    #[test]
    fn a_float_local_gets_a_hash_abstraction_hole() {
        let out = emit_stateright(&BodyFacts {
            functions: vec![ts::single_local_fn(NumKind::Float)],
        });
        assert!(
            out.contains("floats aren't; choose an abstraction"),
            "float local should carry an abstraction hole;\n{out}"
        );
    }

    #[test]
    fn a_multi_block_switchint_surfaces_a_cfg_hole() {
        // A guarded divide: four blocks, entry ends in a SwitchInt. Not
        // straight-line, so a CFG summary + hole is emitted while block 0's stmt
        // still lowers to a real state mutation.
        let out = emit_stateright(&BodyFacts {
            functions: vec![ts::guarded_divide_fn()],
        });
        ts::assert_guarded_cfg_summary(&out);
        // Block 0's `_3 = Ne(_2, 0)` comparison still lowers to a real mutation.
        assert!(
            out.contains("next.app__safe_l3 = next.app__safe_l2 != 0;"),
            "block 0's straight-line stmt should still lower;\n{out}"
        );
    }
}
